language: java
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email:
    on_success: never
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#YHC"
    template:
          - "\u000304%{repository_name}/%{branch} #%{build_number} (%{author}): \u0002%{result}"
          - "\u000303Commit Message: %{commit_message}"
    skip_join: true
