language: java
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email:
    on_success: never
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#YHC"
    template:
          - "%{repository_name}/%{branch} #%{build_number} (%{author}): %{result}"
          - "Commit Message: %{commit_message}"
    skip_join: true
